/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Karol
 */
public class FormSalonSocialBqq extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormResidente
     */
    public FormSalonSocialBqq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jLApartamento = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jTxNombre = new javax.swing.JTextField();
        jTxApartamento = new javax.swing.JTextField();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jBNueva = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jLCorreo = new javax.swing.JLabel();
        jTxCorreo = new javax.swing.JTextField();
        jBEliminar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLDeposito = new javax.swing.JLabel();
        jTxDeposito = new javax.swing.JTextField();
        jLLugar = new javax.swing.JLabel();
        jCBLugar = new javax.swing.JComboBox<>();
        jLAnuncio = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre");

        jLApartamento.setForeground(new java.awt.Color(255, 255, 255));
        jLApartamento.setText("Apartamento");

        jLFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLFecha.setText("Fecha del evento");

        jBNueva.setText("Nueva");
        jBNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jLCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLCorreo.setText("Correo");

        jBEliminar.setText("Eliminar");

        jBConsultar.setText("Consultar");

        jBSalir.setText("Salir");

        jLDeposito.setForeground(new java.awt.Color(255, 255, 255));
        jLDeposito.setText("Deposito");

        jTxDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxDepositoActionPerformed(evt);
            }
        });

        jLLugar.setForeground(new java.awt.Color(255, 255, 255));
        jLLugar.setText("Lugar");

        jCBLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Zona BBQ", "Salon social" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNueva)
                .addGap(18, 18, 18)
                .addComponent(jBGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBActualizar)
                .addGap(18, 18, 18)
                .addComponent(jBEliminar)
                .addGap(18, 18, 18)
                .addComponent(jBConsultar)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLFecha)
                        .addComponent(jLNombre)
                        .addComponent(jLApartamento)
                        .addComponent(jLCorreo)
                        .addComponent(jLDeposito)
                        .addComponent(jLLugar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLAnuncio)
                        .addGap(50, 50, 50)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxApartamento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jTxDeposito)
                    .addComponent(jCBLugar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(310, 310, 310))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFecha)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLugar)
                    .addComponent(jCBLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDeposito))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApartamento))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCorreo)
                    .addComponent(jTxCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLAnuncio)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNueva)
                    .addComponent(jBGuardar)
                    .addComponent(jBActualizar)
                    .addComponent(jBEliminar)
                    .addComponent(jBConsultar)
                    .addComponent(jBSalir))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jTxDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxDepositoActionPerformed

    private void jBNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNuevaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBActualizar;
    public javax.swing.JButton jBConsultar;
    public javax.swing.JButton jBEliminar;
    public javax.swing.JButton jBGuardar;
    public javax.swing.JButton jBNueva;
    public javax.swing.JButton jBSalir;
    public javax.swing.JComboBox<String> jCBLugar;
    public com.toedter.calendar.JDateChooser jDCFecha;
    public javax.swing.JLabel jLAnuncio;
    public javax.swing.JLabel jLApartamento;
    public javax.swing.JLabel jLCorreo;
    public javax.swing.JLabel jLDeposito;
    public javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLLugar;
    public javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxApartamento;
    public javax.swing.JTextField jTxCorreo;
    public javax.swing.JTextField jTxDeposito;
    public javax.swing.JTextField jTxNombre;
    // End of variables declaration//GEN-END:variables
}
