/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Karol
 */
public class FormTrasteo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPermiso
     */
    public FormTrasteo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupIngrsoSalida = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jLApartamento = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jTxNombre = new javax.swing.JTextField();
        jTxApartamento = new javax.swing.JTextField();
        jBNueva = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jLCorreo = new javax.swing.JLabel();
        jTxCorreo = new javax.swing.JTextField();
        jBEliminar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jCbTrasteoOMaterial = new javax.swing.JComboBox<>();
        jTxTipoMaterial = new javax.swing.JTextField();
        jLTipoMaterial = new javax.swing.JLabel();
        jLHora = new javax.swing.JLabel();
        jTxHora = new javax.swing.JTextField();
        jRBIngreso = new javax.swing.JRadioButton();
        jRBSalida = new javax.swing.JRadioButton();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jLAnuncio = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre");

        jLApartamento.setForeground(new java.awt.Color(255, 255, 255));
        jLApartamento.setText("Apartamento");

        jLFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLFecha.setText("Fecha");

        jTxApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxApartamentoActionPerformed(evt);
            }
        });

        jBNueva.setText("Nueva");
        jBNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jLCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLCorreo.setText("Correo");

        jBEliminar.setText("Eliminar");

        jBConsultar.setText("Consultar");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jCbTrasteoOMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Trasteo", "Material" }));

        jTxTipoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTipoMaterialActionPerformed(evt);
            }
        });

        jLTipoMaterial.setForeground(new java.awt.Color(255, 255, 255));
        jLTipoMaterial.setText("Tipo de material");

        jLHora.setForeground(new java.awt.Color(255, 255, 255));
        jLHora.setText("Hora");

        GroupIngrsoSalida.add(jRBIngreso);
        jRBIngreso.setText("Ingreso");
        jRBIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIngresoActionPerformed(evt);
            }
        });

        GroupIngrsoSalida.add(jRBSalida);
        jRBSalida.setText("Salida");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBNueva)
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jBConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCbTrasteoOMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLApartamento)
                                .addGap(18, 18, 18)
                                .addComponent(jTxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRBIngreso)))
                        .addGap(18, 18, 18)
                        .addComponent(jRBSalida))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLTipoMaterial)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLFecha)
                                .addComponent(jLHora)
                                .addComponent(jLNombre)
                                .addComponent(jLCorreo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxHora, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(jTxNombre)
                                .addComponent(jTxCorreo)
                                .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLAnuncio))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApartamento)
                    .addComponent(jTxApartamento)
                    .addComponent(jRBIngreso)
                    .addComponent(jRBSalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbTrasteoOMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipoMaterial)
                    .addComponent(jTxTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFecha)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHora)
                    .addComponent(jTxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCorreo)
                    .addComponent(jTxCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLAnuncio)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNueva)
                    .addComponent(jBGuardar)
                    .addComponent(jBActualizar)
                    .addComponent(jBEliminar)
                    .addComponent(jBConsultar)
                    .addComponent(jBSalir))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jTxApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxApartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxApartamentoActionPerformed

    private void jRBIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBIngresoActionPerformed

    private void jTxTipoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTipoMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTipoMaterialActionPerformed

    private void jBNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNuevaActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup GroupIngrsoSalida;
    public javax.swing.JButton jBActualizar;
    public javax.swing.JButton jBConsultar;
    public javax.swing.JButton jBEliminar;
    public javax.swing.JButton jBGuardar;
    public javax.swing.JButton jBNueva;
    public javax.swing.JButton jBSalir;
    public javax.swing.JComboBox<String> jCbTrasteoOMaterial;
    public com.toedter.calendar.JDateChooser jDCFecha;
    public javax.swing.JLabel jLAnuncio;
    public javax.swing.JLabel jLApartamento;
    public javax.swing.JLabel jLCorreo;
    public javax.swing.JLabel jLFecha;
    public javax.swing.JLabel jLHora;
    public javax.swing.JLabel jLNombre;
    public javax.swing.JLabel jLTipoMaterial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRBIngreso;
    public javax.swing.JRadioButton jRBSalida;
    public javax.swing.JTextField jTxApartamento;
    public javax.swing.JTextField jTxCorreo;
    public javax.swing.JTextField jTxHora;
    public javax.swing.JTextField jTxNombre;
    public javax.swing.JTextField jTxTipoMaterial;
    // End of variables declaration//GEN-END:variables
}
